### ISSUE TITLE
openvpn.redirectGateway as true cause all network traffic fails

### ISSUE THREAD

**Issue by shaqtsui** [sergelogvinov/helm-charts#116]
### Description
Set openvpn.redirectGateway to true, cause all client traffic go to vpn server, but ip_forward is false in vpn server.
Which lead to all traffic failed.

Note:
/proc/sys/net/ipv4/ip_forward in readonly fs, so I can not even login to pod & enable.

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by shaqtsui** [comment]
Correct me if I am wrong.
Here 
```
/proc/sys/net/ipv4/ip_forward in readonly filesystem
```
I mean in the openvpn container's fs. As container initialization defined via helm. I think the container should started in privileged mode?

**Comment by shaqtsui** [comment]
Or something like ?:
```
apiVersion: v1
kind: Pod
metadata:
  name: ip-forward-pod
spec:
  securityContext:
    sysctls:
    - name: net.ipv4.ip_forward
      value: "1"  # Enable IP forwarding
  containers:
  - name: openvpn-udp
    image: ghcr.io/sergelogvinov/openvpn:2.6.12
```

**Comment by sergelogvinov** [comment]
Probably openvpn trying hack /proc/sys/net/ipv4/ip_forward
Helm chart does not have this command.

Yep, you can try `securityContext` but you need to allow it in kubelet config

by default openvpn container has:

```yaml
securityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    add:
      - NET_ADMIN
      - MKNOD
      - SETUID
      - SETGID
    drop:
      - ALL
```

try to add mode capabilities to the container
