### ISSUE TITLE
Option to change -Xmx JVM value in TeamCity Chart for Server

### ISSUE THREAD

**Issue by TAMQuiroz** [sergelogvinov/helm-charts#53]
Is there a way, or can one be implemented, to control the JVM memory value for the TeamCity Server configuration in case more than the default one is needed? It looks like no matter how much memory my pod has, the TeamCity max memory is 2 GB. Thank you!

**Comment by sergelogvinov** [comment]
Hi,

I've added envs param:

```yaml
server:
  envs:
    TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:ReservedCodeCacheSize=640m"
```
